const config = {
  BASE_URL: process.env.REACT_APP_BASE_URL,
  GOOGLE_KEY: process.env.REACT_APP_GOOGLE_KEY,
  GOOGLE_SECRET: process.env.REACT_APP_GOOGLE_SECRET,
  FACEBOOK_KEY: process.env.REACT_APP_FACEBOOK_KEY,
  FACEBOOK_SECRET: process.env.REACT_APP_FACEBOOK_SECRET,
  TWITTER_KEY: process.env.REACT_APP_TWITTER_KEY,
  TWITTER_SECRET: process.env.REACT_APP_TWITTER_SECRET
};

export default config;
